import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import WhatsAppButton from "@/components/WhatsAppButton";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
       <Head>
        <meta name="facebook-domain-verification" content="5n499kynw54azs1bbeks5i3zwh0g32" />
      </Head>
      <body className={inter.className}>
        {children}
        <WhatsAppButton />
        </body>
    </html>
  );
}
